#!/usr/bin/env bash
echo "== delete bucket"

# Check for bucket name 
if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME \
--query Location \
--output text