#!/usr/bin/env bash
echo "== sync"


set -e


# Check for bucket name 
if [ -z "$1" ]; then
    echo "No bucket name provided"
    exit 1
fi

BUCKET_NAME=$1
# Check for filename prefix 
if [ -z "$2" ]; then
    echo "No file name provided"
    exit 1
fi

fileprefix=$2







#storage
output_dir="/tmp/s3-bash-scripts"


#remove folder 

rm -r $output_dir


#folder creation
mkdir -p $output_dir



#random gen number
num_files=$((RANDOM % 6 + 5))

for((i=1; i<=$num_files; i++));do
    #gen random file name
    random_filename="$output_dir/${fileprefix}_$i.txt"


    #gen random data 
    def if=/dev/urandom of="$random_filename" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $output_dir

aws s3 sync $output_dir s3:://$BUCKET_NAME/files